version: "3.1"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jgibson
      POSTGRES_DB: snippets
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
